version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  healthy-function:
    lang: golang-middleware
    handler: ./timeout-test
    image: nlochschmidt/timeout-test:0.0.2
    environment:
      fprocess: ./start 0
      write_timeout: 10s
      read_timeout: 10s
      exec_timeout: 10s
      handler_wait_duration: 0s
  write-time-out-on-each-request:
    lang: golang-middleware
    handler: ./timeout-test
    image: nlochschmidt/timeout-test:0.0.2
    environment:
      fprocess: ./start 0
      write_timeout: 10s
      #read_timeout: 10s
      #exec_timeout: 55s
      handler_wait_duration: 15s
  exec-time-out-on-each-request:
    lang: golang-middleware
    handler: ./timeout-test
    image: nlochschmidt/timeout-test:0.0.2
    environment:
      fprocess: ./start 0
      write_timeout: 1m
      #read_timeout: 10s
      exec_timeout: 5s
      handler_wait_duration: 15s
  internal-server-error-on-early-request-timeout-afterwards:
    lang: golang-middleware
    handler: ./timeout-test
    image: nlochschmidt/timeout-test:0.0.2
    environment:
      fprocess: ./start 60
      #write_timeout: 10s
      #read_timeout: 10s
      exec_timeout: 5s
      handler_wait_duration: 10s

configuration:
  templates:
  - name: golang-middleware

